matrix:
  include:
    - language: python
      dist: xenial
      python : 3.6
      before_script:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py makemigrations server
        - python manage.py migrate --run-syncdb
        - python manage.py test server.tests

    - language: node_js
      node_js:
        - v10
      before_install:
        - cd frontend
      before_script:
      script:
        - npm install
        - npm test
